# Generated by Django 3.1.3 on 2020-11-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20201108_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coach_information',
            field=models.TextField(default=0, verbose_name='Имя и контакты наставника'),
            preserve_default=False,
        ),
    ]
