# Generated by Django 3.1.3 on 2020-11-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_profile_coach_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
